### ISSUE TITLE
bot.servers[Servertocheck].members; is sometimes undefined

### ISSUE THREAD

**Issue by MrCryptoT** [MrCryptoT/PersonatorBot#23]
AllUserstmp = bot.servers[Servertocheck].members;
 is sometimes undefined (propbably we are refreshing our cache right now and some API call is beeing async handlet - hence the library cache is empty right now - add a loop in ANY event handler to check if we are "refreshingcaches" and if so just wait for it to finish. (reset this var at the end of the getdataarray function)

**Comment by MrCryptoT** [comment]
Should be fixed by adding a Loop that never ends until we know we are at the end of the refreshdata function

**Comment by MrCryptoT** [comment]
actually, we also need to check if we are already processing an event before triggering the refresh of our data. 
(I think thats "rugpulling" the data from the bot while its processing an event async)

**Comment by MrCryptoT** [comment]
Despite checks around an already running event or cacherefresh, we still seem to get this Error, so we shouldn't be rugpulling ourselves.
Im not quite sure why this is yet, If we would be over the allowed API Rate Limit we should crash with another Error. 
```
        AllUserstmp = bot.servers[Servertocheck].members;
                                                 ^

TypeError: Cannot read property 'members' of undefined
    at Getalluserdataandbuildarrays (C:\_Custom\PersonatorBot\bot.js:534:43)
    at Timeout._onTimeout (C:\_Custom\PersonatorBot\bot.js:108:20)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

Is the used Library Rug pulling us on some API Call? (As it seems  `bot.servers[Servertocheck]` is undefined I may just need to wait a bit before that call? - next try)

**Comment by MrCryptoT** [comment]
Reopen 
No idea why this still crashes at some points. 
Will need some long bored night fixing it I guess, don't have the nerves rn

**Comment by MrCryptoT** [comment]
Could not reproduce for 4 Days without real changes. 
The only difference in activity on the Server might be the amount of text messages. 
I have yet to figure out what exactly was causing this, unless its some timed event, that is colliding with the timed refresh?

Atlast, it will be some rare event where 2 threads run at the same time "fighting" each other, altho most should already check if "they are beeing rugpulled" and wait for the already running thread to stop by looping until ready. 🤔

**Comment by MrCryptoT** [comment]
Close - runs for 7 Days on Prod without any Crash, likely fixxed

**Comment by MrCryptoT** [comment]
Retrospectivly determined the rootcause was an unset `eventisbeeingprocessed ` variable while processing an event (memberadd/renames)
So it rarely queried the memberlist while it was beeing rebuilt by the underlying library.
